# Base image với CUDA + cuDNN + Python 3.10
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV HF_HUB_CACHE=/root/.cache/huggingface/hub

# Cài Python 3.10 và pip
RUN export DEBIAN_FRONTEND=noninteractive TZ=US && \
    apt-get update && \
    apt-get install -y \
        python3.10 \
        python3-pip \
        espeak \
        libespeak1 && \
    rm -rf /var/lib/apt/lists/*

    
# Tạo symlink python -> python3 để tiện sử dụng
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set working directory
WORKDIR /app

# Sao chép requirements 
COPY requirements.txt .

# Cài đặt tất cả packages
RUN pip install -r requirements.txt

# Sao chép và tải model
COPY downloadmodel.py .
RUN python downloadmodel.py

# Sao chép source code
COPY Whisper_API.py .

# Expose port
EXPOSE 8000

# Run app
CMD ["uvicorn", "Whisper_API:app", "--host", "0.0.0.0", "--port", "8000"]