# Base image with CUDA, cuDNN, Python 3.10
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Python 3.10 
RUN export DEBIAN_FRONTEND=noninteractive TZ=US && \
    apt-get update && \
    apt-get -y install python3.10 python3-pip

# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY Whisper_API.py .

ENV HF_HUB_CACHE=~/.cache/huggingface/hub

# ADD and RUN file download
RUN mkdir -p ~/.cache/huggingface
RUN mkdir -p ~/.cache/huggingface/hub
# RUN mkdir -p ~/.cache/huggingface/hub/models--Systran--faster-whisper-medium
RUN mkdir -p ./models--Systran--faster-whisper-medium
COPY models--Systran--faster-whisper-medium ./models--Systran--faster-whisper-medium

RUN cp -r ./models--Systran--faster-whisper-medium ~/.cache/huggingface/hub/
RUN rm -rf ./models--Systran--faster-whisper-medium

# COPY models--Systran--faster-whisper-medium ~/.cache/huggingface/hub/models--Systran--faster-whisper-medium
# COPY ./test ~/.cache/huggingface/hub/models--Systran--faster-whisper-medium-copy

# COPY models--Systran--faster-whisper-medium .
# COPY ./test .


# Expose FastAPI default port
EXPOSE 8000

# Run the app using uvicorn
CMD ["uvicorn", "Whisper_API:app", "--host", "0.0.0.0", "--port", "8000"]




