apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-config # Tên phải chính xác như thế này
  namespace: kube-system # Phải nằm trong namespace kube-system
data:
  config.yaml: |
    version: v1
    sharing:
      timeSlicing:
        resources:
          # Tên tài nguyên mà bạn muốn chia sẻ
          - name: nvidia.com/gpu
            # Chia thành 3 phần (replicas)
            replicas: 3