services:
  jenkins:
    build:
      context: ../../src/services/jenkin_upgrade
      dockerfile: dockerfile
    image: tructran172003/jenkin:v1.0
    container_name: jenkins
    privileged: true
    group_add:
      - 984   
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/Documents/RAG_Project/src/services/Text_to_Speech/StyleTTS2/Utils/ASR/epoch_00080.pth:/app/StyleTTS2/Utils/ASR/epoch_00080.pth:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - elk-net
    environment:
      - NO_PROXY=localhost,127.0.0.1,updates.jenkins.io

networks:
  elk-net:
    external: true
