services:
  whisper-api:
    build:
      context: ../../src/services/Faster_Whisper
      dockerfile: dockerfile
    image: tructran172003/whisper-api:latest
    ports:
      - "8000:8000"
    labels:
      co.elastic.logs/enabled: "true"
    environment:
      - OTEL_SERVICE_NAME=whisper-api
      - JAEGER_COLLECTOR_URL=http://jaeger:14268/api/traces

      # bật/tắt tracing runtime
      - ENABLE_TRACING=true
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - elk-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all

  tts-api:
    build:
      context: ../../src/services/Text_to_Speech
      dockerfile: dockerfile
    image: tructran172003/tts-api:latest
    ports:
      - "8001:8001"
    labels:
      co.elastic.logs/enabled: "true"
    environment:
      # Tracing (OpenTelemetry / Jaeger)
      - OTEL_SERVICE_NAME=tts-api
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - ENABLE_TRACING=true

      # bật/tắt tracing runtime
      - ENABLE_TRACING=true
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - elk-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all 

  chatbot_api:
    build:
      context: ../../src/services/chatbot_api
      dockerfile: dockerfile
    image: tructran172003/chatbot-api:latest
    env_file:
      - ../../config/.env
    labels:
      co.elastic.logs/enabled: "true"
    ports:
      - "4096:4096"
    depends_on:
      - whisper-api
      - db
    networks:
      - elk-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all 

  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-rag
    restart: always
    env_file:
      - ../../config/.env
    labels:
      co.elastic.logs/enabled: "true"
    ports:
      - "5432:5432"
    # Defines a volume to persist the database data.
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - elk-net

  # frontend:
  #   build:
  #     context: ../../src/services/Front_end  
  #     dockerfile: dockerfile
  #   image: tructran172003/frontend:v1.0
  #   ports:
  #     - "9001:9001"
  #   depends_on:
  #     - chatbot_api
  #     - whisper-api
  #     - tts-api
  #   networks:
  #     - elk-net


volumes:
  pgdata:

networks:
  elk-net:
    external: true

