services:
  whisper-api:
    build:
      context: ../../src/services/Faster_Whisper
      dockerfile: dockerfile
    image: tructran172003/whisper-api:v1.0
    ports:
      - "8000:8000"
    labels:
      co.elastic.logs/enabled: "true"
    networks:
      - elk-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all

  tts-api:
    build:
      context: ../../src/services/Text_to_Speech
      dockerfile: dockerfile
    image: tructran172003/tts-api:v1.0
    ports:
      - "8001:8001"
    labels:
      co.elastic.logs/enabled: "true"
    environment:
      # Tracing (OpenTelemetry / Jaeger)
      - OTEL_SERVICE_NAME=tts-api
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - OTEL_PROPAGATORS=b3

      # optional: bật/tắt tracing runtime
      - ENABLE_TRACING=true
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - elk-net
    depends_on:
      - jaeger
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all

  chatbot_api:
    build:
      context: ../../src/services/chatbot_api
      dockerfile: dockerfile
    image: tructran172003/chatbot-api:v1.0
    env_file:
      - ../../config/.env
    labels:
      co.elastic.logs/enabled: "true"
    ports:
      - "4096:4096"
    depends_on:
      - whisper-api
      - db
    networks:
      - elk-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all

  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-rag
    restart: always
    env_file:
      - ../../config/.env
    labels:
      co.elastic.logs/enabled: "true"
    ports:
      - "5432:5432"
    # Defines a volume to persist the database data.
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - elk-net


  # frontend:
  #   build:
  #     context: ../RAG_Project/Container_Folder/Front_end   # chỗ có Dockerfile frontend
  #     dockerfile: dockerfile
  #  # image: tructran172003/frontend:v1.0
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - chatbot_api
  #     - whisper-api
  #     - tts-api
  #   networks:
  #     - my-network
volumes:
  pgdata:

networks:
  elk-net:
    external: true

