# =========================
# ELK Stack
# =========================
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    env_file:
      - ../../config/.env
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./extensions/elasticsearch/config/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-net


  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    env_file:
      - ../../config/.env
    volumes:
      - ./extensions/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z 
    environment:
    - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
    ports:
      - "5601:5601"
    networks:
      - elk-net
    depends_on:
      - elasticsearch


  filebeat:
    image: docker.elastic.co/beats/filebeat:8.19.0
    container_name: filebeat
    user: root
    command:
      - -e
      - --strict.perms=false
    env_file:
      - ../../config/.env
    volumes:
      - ./extensions/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,z
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - elk-net
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  elk-net:
    external: true