FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# System packages
RUN apt-get update && apt-get install -y \
        python3.10 \
        python3-pip \
        espeak \
        libespeak1 \
    && rm -rf /var/lib/apt/lists/*

# # Upgrade pip, setuptools, wheel
# RUN python3.10 -m pip install --upgrade pip setuptools wheel

# Copy requirements first to leverage Docker cache
COPY requirements.txt /app/requirements.txt

# Install dependencies using legacy resolver to avoid AssertionError
RUN pip install --use-deprecated=legacy-resolver -r requirements.txt

# Copy app files
COPY API_LLAMA3_2.py db.py model.py utils.py prompt.py /app/

RUN python3.10 -m spacy download en_core_web_sm

# Expose port
EXPOSE 4096

# Run
CMD ["python3.10", "-m", "uvicorn", "API_LLAMA3_2:app", "--host", "0.0.0.0", "--port", "4096"]
# python3.10 -m uvicorn API_LLAMA3_2:app --host 0.0.0.0 --port 4096





